# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# [aws]
# style = "bold #ffb86c"

# [character]
# error_symbol = "[Î»](bold #ff5555)"
# success_symbol = "[Î»](bold #f8f8f2)"

[cmd_duration]
style = "bold #f1fa8c"

# [directory]
# style = "bold #50fa7b"

# [git_branch]
# style = "bold #ff79c6"
#
# [git_status]
# style = "bold #ff5555"

[hostname]
style = "bold #ff5555"

[username]
format = "[$user]($style) on "
style_user = "bold #bd93f9"

# FIRST LINE/ROW: Info & Status
# First param â”€â”Œ

# [username]
# format = "[â•­â”€](bold blue)"
# style_user = "bold yellow"
# style_root = "bold yellow"
show_always = true

# Second param
# [hostname]
# format = "[$hostname]($style) [in](blue) "
# style = "bold yellow"
# trim_at = "-"
# ssh_only = false
# disabled = true

# Third param
# [directory]
# style = "bold blue"
# truncation_length = 0
# truncate_to_repo = true
# truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
# [git_status]
# style = "white"
# ahead = "â‡¡${count}"
# diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
# behind = "â‡£${count}"
# deleted = "x"

# Last param in the first line/row
# [cmd_duration]
# min_time = 1
# format = "took [$duration]($style)"
# disabled = true


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
# Prompt: optional param 1
[time]
format = "[â”‚](bold blue)$time($style)ğŸ•™\n"
time_format = "%T"
style = "bright-white"
disabled = true

# Prompt: param 2 â””â”€
[character]
success_symbol = "[ï”](bold green)"
error_symbol = "[î¯](bold red)"

# SYMBOLS
# [status]
# symbol = "X"
# format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
# map_symbol = true
# disabled = true

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[directory]
read_only = " ï ½"

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

[spack]
symbol = "ğŸ…¢ "

[rust]
symbol = "î¨ "
##########################################################3
#[status]
#style = "bg:blue"
#symbol = "ğŸ”´"
#format = '[\[$symbol $status_common_meaning$status_signal_name$status_maybe_int\]]($style) '
#map_symbol = true
#disabled = false

# Disable the newline at the start of the prompt
# add_newline = false
#
# [line_break]
# disabled = true
#
# [battery]
# full_symbol = "ğŸ”‹"
# charging_symbol = "âš¡ï¸"
# discharging_symbol = "ğŸ’€"
#
# # [aws]
# # symbol = "îŒ½ "
#
# # [conda]
# # symbol = "ï„Œ "
#
# # [dart]
# # symbol = "î˜ "
#
# [directory]
# read_only = " ï ½"
# style = "bold italic #87A752"
#
# # [docker]
# # symbol = "ïŒˆ "
#
# # [elixir]
# # symbol = "î‰µ "
#
# # [elm]
# # symbol = "î˜¬ "
#
# [git_branch]
# symbol = "ï˜ "
#
# # [golang]
# # symbol = "î˜§ "
#
# # [haskell]
# # symbol = "î˜Ÿ "
#
# # [hg_branch]
# # symbol = "ï˜ "
#
# [java]
# symbol = "î‰– "
#
# # [julia]
# # symbol = "î˜¤ "
#
# [memory_usage]
# symbol = "ï¡š "
#
# # [nim]
# # symbol = "ïš¤ "
#
# [nix_shell]
# symbol = "ï‹œ "
#
# [nodejs]
# symbol = "î‰ "
#
# [package]
# symbol = "ï£– "
#
# [perl]
# symbol = "î© "
#
# [php]
# symbol = "î˜ˆ "
#
# [python]
# symbol = "î˜† "
#
# # [ruby]
# # symbol = "îˆ¾ "
#
# [rust]
# symbol = "î¨ "
#
# # [swift]
# # symbol = "ï¯£ "
#
